spring.application.name=API-Gateway-41

server.port=8000
management.endpoints.web.exposure.include=health,info

# ==============================
# Eureka
# ==============================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=false


# ==============================
# Spring Cloud Gateway MVC
# ==============================

spring.cloud.gateway.server.webmvc.enabled=true


# ==============================
# AUTH SERVICE
# ==============================

spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://AUTH-SERVICE-41
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**


# ==============================
# METER SERVICE
# ==============================

spring.cloud.gateway.server.webmvc.routes[1].id=meter-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://METER-SERVICE-41
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/meters/**


# ==============================
# USAGE SERVICE
# ==============================

spring.cloud.gateway.server.webmvc.routes[2].id=usage-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://USAGE-SERVICE-41
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/usage/**


# ==============================
# ALERT SERVICE
# ==============================

spring.cloud.gateway.server.webmvc.routes[3].id=alert-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://ALERT-SERVICE-41
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/alerts/**